@startuml
participant Actor
Actor -> LoginControllerTest : testLoginWithOutdatedToken
activate LoginControllerTest
LoginControllerTest -> LoginControllerTest : () ->
activate LoginControllerTest
LoginControllerTest --> LoginControllerTest
deactivate LoginControllerTest
return
@enduml