@startuml
participant Actor
Actor -> LoginControllerTest : testLoginWithoutToken
activate LoginControllerTest
LoginControllerTest -> LoginControllerTest : () ->
activate LoginControllerTest
LoginControllerTest --> LoginControllerTest
deactivate LoginControllerTest
return
@enduml