@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.mario.usuarios.controller.LoginControllerTest#testLoginSuccess()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.mario.usuarios.controller.LoginControllerTest",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_103666436 { 
   	label=mario
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1532315985 { 
   	label=usuarios
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1584861729 { 
   	label=UsuarioDetailsImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   UsuarioDetailsImpl648435075XXXbuild1531808526[
	label="+ build()"
	style=filled
	fillcolor=white
	tooltip="UsuarioDetailsImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1820029463 { 
   	label=LoginControllerTest
	labeljust=l
	fillcolor=white
	style=filled
   
   LoginControllerTest1128708622XXXtestLoginSuccess0[
	label="+ testLoginSuccess()"
	style=filled
	fillcolor=white
	tooltip="LoginControllerTest

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_487851843 { 
   	label=JwtTokenUtil
	labeljust=l
	fillcolor=white
	style=filled
   
   JwtTokenUtil1415248639XXXgenerateToken1371243561[
	label="+ generateToken()"
	style=filled
	fillcolor=white
	tooltip="JwtTokenUtil

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_802108970 { 
   	label=UsuarioDetailsServiceImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   UsuarioDetailsServiceImpl648435075XXXloadUserByUsername1808118735[
	label="+ loadUserByUsername()"
	style=filled
	fillcolor=white
	tooltip="UsuarioDetailsServiceImpl

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
LoginControllerTest1128708622XXXtestLoginSuccess0 -> JwtTokenUtil1415248639XXXgenerateToken1371243561;
LoginControllerTest1128708622XXXtestLoginSuccess0 -> UsuarioDetailsServiceImpl648435075XXXloadUserByUsername1808118735;
UsuarioDetailsServiceImpl648435075XXXloadUserByUsername1808118735 -> UsuarioDetailsImpl648435075XXXbuild1531808526;
    
}
@enduml