@startuml
participant Actor
Actor -> ValidaEmailPassword : validaEmailPassword
activate ValidaEmailPassword
ValidaEmailPassword -> RegExUtils : validateEmailFormat
activate RegExUtils
RegExUtils --> ValidaEmailPassword
deactivate RegExUtils
create ErrorStruct
ValidaEmailPassword -> ErrorStruct : new
activate ErrorStruct
ErrorStruct --> ValidaEmailPassword
deactivate ErrorStruct
ValidaEmailPassword -> RegExUtils : validatePasswordRules
activate RegExUtils
RegExUtils --> ValidaEmailPassword
deactivate RegExUtils
create ErrorStruct
ValidaEmailPassword -> ErrorStruct : new
activate ErrorStruct
ErrorStruct --> ValidaEmailPassword
deactivate ErrorStruct
return
@enduml