@startuml
participant Actor
Actor -> SignUpControllerTest : testSignUpWithExistingUser
activate SignUpControllerTest
create Usuario
SignUpControllerTest -> Usuario : new
activate Usuario
Usuario --> SignUpControllerTest
deactivate Usuario
create Usuario
SignUpControllerTest -> Usuario : new
activate Usuario
Usuario --> SignUpControllerTest
deactivate Usuario
SignUpControllerTest -> UsuarioRepository : findByName
activate UsuarioRepository
UsuarioRepository --> SignUpControllerTest
deactivate UsuarioRepository
SignUpControllerTest -> SignUpControllerTest : () ->
activate SignUpControllerTest
SignUpControllerTest -> SignUpController : signUp
activate SignUpController
SignUpController -> ValidaEmailPassword : validaEmailPassword
activate ValidaEmailPassword
ValidaEmailPassword -> RegExUtils : validateEmailFormat
activate RegExUtils
RegExUtils --> ValidaEmailPassword
deactivate RegExUtils
create ErrorStruct
ValidaEmailPassword -> ErrorStruct : new
activate ErrorStruct
ErrorStruct --> ValidaEmailPassword
deactivate ErrorStruct
ValidaEmailPassword -> RegExUtils : validatePasswordRules
activate RegExUtils
RegExUtils --> ValidaEmailPassword
deactivate RegExUtils
create ErrorStruct
ValidaEmailPassword -> ErrorStruct : new
activate ErrorStruct
ErrorStruct --> ValidaEmailPassword
deactivate ErrorStruct
ValidaEmailPassword --> SignUpController
deactivate ValidaEmailPassword
SignUpController -> UsuarioRepository : findByName
activate UsuarioRepository
UsuarioRepository --> SignUpController
deactivate UsuarioRepository
create ErrorStruct
SignUpController -> ErrorStruct : new
activate ErrorStruct
ErrorStruct --> SignUpController
deactivate ErrorStruct
create ValidacionException
SignUpController -> ValidacionException : new
activate ValidacionException
ValidacionException --> SignUpController
deactivate ValidacionException
create ResponseSignUp
SignUpController -> ResponseSignUp : new
activate ResponseSignUp
ResponseSignUp --> SignUpController
deactivate ResponseSignUp
SignUpController -> UsuarioDetailsImpl : build
activate UsuarioDetailsImpl
create UsuarioDetailsImpl
UsuarioDetailsImpl -> UsuarioDetailsImpl : new
activate UsuarioDetailsImpl
UsuarioDetailsImpl --> UsuarioDetailsImpl
deactivate UsuarioDetailsImpl
UsuarioDetailsImpl --> SignUpController
deactivate UsuarioDetailsImpl
SignUpController -> JwtTokenUtil : generateToken
activate JwtTokenUtil
JwtTokenUtil --> SignUpController
deactivate JwtTokenUtil
SignUpController --> SignUpControllerTest
deactivate SignUpController
SignUpControllerTest --> SignUpControllerTest
deactivate SignUpControllerTest
return
@enduml